[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
latest = "6JiDoZwQzjejMad35YLr9umaTR3t3LHW2inxCNyn2zV1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jarettdunn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
